### ISSUE TITLE
Deeplinks not working?

### ISSUE THREAD

**Issue by fabian** [worldskills/worldskills-quizzes#23]
There seems to be an issue with deeplinks - after login I always get redirected back to the list with quizzes, e.g. https://quiz.worldskills.show/quiz/222

**Comment by TehWazzard** [comment]
hmm - they seem to work on forums.
implementation: https://github.com/worldskills/worldskills-forums/blob/master/src/app/home/home.component.ts

the `AppAuthGuard` populates the `returnUrl` variable which the app will still need to handle.

**Comment by TehWazzard** [comment]
I can move the `returnUrl` handling logic to the library - probably as a helper function. then an apps unguarded component could use it and decide wheather or not to perform the redirect...

**Comment by fabian** [comment]
@TehWazzard  That would be great, thanks!

**Comment by fabian** [comment]
Fixed with updating the lib.
